/*
 _   _             _           
| | | |           | |          
| | | |_   _ _   _| |__   __ _ 
| | | | | | | | | | '_ \ / _` |
\ \_/ / |_| | |_| | | | | (_| |
 \___/ \__, |\__,_|_| |_|\__,_|
        __/ |                  
       |___/                   
*/

// TimeHelper
// Thin class to help with timing and translations of TZ as needed

public class vy_TimeHelper {
    
    public vy_TimeHelper() {

    }

    public DateTime now () {
        return DateTime.now ();
    }
}
